### ISSUE TITLE
Needed documentation of deployment process for spotify-playing 

### ISSUE THREAD

**Issue by gauravghongde** [kittinan/kittinan#1]
It would be helpful, if you could document spotify-api connectivity and process of generating REFRESH_TOKEN.
The template is so awesome, thanks for converting it into flask. 👍

**Comment by kittinan** [comment]
@gauravghongde  this is document for create spotify refresh_token https://github.com/kittinan/kittinan/blob/master/api/README.md

i'm using Vercel serverless to serve the function

**Comment by kittinan** [comment]
@gauravghongde Please check out https://github.com/kittinan/spotify-github-profile

it automatically generates markdown code
